baseURL = 'https://avuign.github.io/'
locale = 'en-us'
title = 'Antoine Vuignier'
theme = "PaperMod"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  defaultTheme = "auto"
  showShareButtons = false
  showReadingTime = false

  [params.profileMode]
    enabled = true
    title = "Antoine Vuignier"
    subtitle = "PhD candidate in Theoretical Physics at EPFL • Transitioning to ML"
    imageUrl = "/images/profile.JPG"
    imageWidth = 150
    imageHeight = 150

    [[params.profileMode.buttons]]
      name = "Projects"
      url = "/projects"

    [[params.profileMode.buttons]]
      name = "CV"
      url = "/CV.pdf"  # put your CV in static/

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/avuign"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/avuignier/"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:ant.vuign@gmail.com"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3
