baseURL = 'https://avuign.github.io/'
locale = 'en-us'
title = 'Antoine Vuignier'
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  defaultTheme = "auto"
  showShareButtons = false
  showReadingTime = false
  showBreadCrumbs = false
  showPostNavLinks = false

  [params.profileMode]
    enabled = true
    title = "Antoine Vuignier"
    subtitle = "Theoretical Physicist, transitioning to ML"
    imageUrl = "/images/profile.jpeg"
    imageWidth = 150
    imageHeight = 150

    [[params.profileMode.buttons]]
      name = "About"
      url = "/about/"

    [[params.profileMode.buttons]]
      name = "CV"
      url = "/cv/"

    [[params.profileMode.buttons]]
      name = "Publications"
      url = "/publications/"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/avuign"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/avuignier/"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:ant.vuign@gmail.com"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 2
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3
