baseURL = 'https://avuign.github.io/'
locale = 'en-us'
title = 'Antoine Vuignier'
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  defaultTheme = "auto"
  showShareButtons = false
  showReadingTime = false
  showBreadCrumbs = false


  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/avuign"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/avuignier/"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:ant.vuign@gmail.com"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 2
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3
    [[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
